apiVersion: v1
kind: PersistentVolume
metadata:
  name: hbase-pv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/media/nfs/data/tsdb/hbase"
