apiVersion: v1
kind: Pod
metadata:
  name: opentsdb
  labels:
    app: tsdb
spec:
  restartPolicy: Never
  containers:
    - name: tsdb
      image: "ciena/opentsdb"
      ports:
        - name: http
          containerPort: 4242
          protocol: TCP
      volumeMounts:
        - mountPath: "/var/lib/hbase"
          name: hbase
        - mountPath: "/var/lib/zookeeper"
          name: zookeeper
  volumes:
    - name: hbase
      persistentVolumeClaim:
        claimName: hbase-pvc
    - name: zookeeper
      persistentVolumeClaim:
        claimName: zk-pvc
